export const TOPUP_STATUS = {
  AWAITING_PAYMENT: "awaiting_payment",
  FINALIZING: "finalizing",
  PAID: "paid",
  EXPIRED: "expired",
  CANCELED: "canceled",
  FAILED: "failed"
} as const;

export type TopupStatus = (typeof TOPUP_STATUS)[keyof typeof TOPUP_STATUS];

export const ACTIVE_TOPUP_STATUSES: TopupStatus[] = [TOPUP_STATUS.AWAITING_PAYMENT, TOPUP_STATUS.FINALIZING];

export const TERMINAL_TOPUP_STATUSES: TopupStatus[] = [
  TOPUP_STATUS.PAID,
  TOPUP_STATUS.EXPIRED,
  TOPUP_STATUS.CANCELED,
  TOPUP_STATUS.FAILED
];

export const PAYMENT_ERROR_CODES = {
  ACTIVE_TOPUP_PENDING: "ACTIVE_TOPUP_PENDING",
  TOPUP_CREATE_FAILED: "TOPUP_CREATE_FAILED",
  TOPUP_NOT_FOUND: "TOPUP_NOT_FOUND",
  TOPUP_ALREADY_PAID: "TOPUP_ALREADY_PAID",
  TOPUP_INVALID_PACKAGES_COUNT: "TOPUP_INVALID_PACKAGES_COUNT"
} as const;
